ROWS = 15
COLS = 15
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
HEALTH = 100
MONEY = 400
TOTAL_LEVELS = 30 # Total rounds

# Enemy constants
SPAWN_COOLDOWN = 400

# Turret constants
TURRET_LEVELS = 4
BUY_COST = 135
UPGRADE_COST = 75
KILL_REWARD = 1
LEVEL_COMPLETE_REWARD = 120
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15 # Milliseconds
DAMAGE = 5