ROWS = 15
COLS = 15
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60

# Enemy constants
SPAWN_COOLDOWN = 400

# Turret constants
TURRET_LEVELS = 4
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15 # Milliseconds